### ISSUE TITLE
importing packages by name results in "module not found"

### ISSUE THREAD

**Issue by zedd45** [defunctzombie/npm-css#15]
running (globally installed) npm-css via:

``` bash
npm-css index.css -o test.css
```

is resulting in:

``` bash
/usr/local/lib/node_modules/npm-css/node_modules/resolve/lib/sync.js:32
    throw new Error("Cannot find module '" + x + "'");
          ^
Error: Cannot find module 'normalize-css'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/npm-css/node_modules/resolve/lib/sync.js:32:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-css/index.js:66:36)
    at walker (/usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:190:22)
    at /usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:298:31)
    at walker (/usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:203:13)
    at /usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/local/lib/node_modules/npm-css/node_modules/traverse/index.js:298:31)
```

I've tried with two modules (Leaflet & Normalize), and both are having the same issue.  

Here's the CSS:

``` css
/* import packages here to get their CSS from the package.json "style" property */
@import "normalize-css";
@import "leaftlet";
```

Here's an excerpt from package.json:

``` json
{
  "style": "public/css/core.css",
  "dependencies": {
    "leaflet": "~0.7.2",
    "normalize-css": "~2.3.0",
    "npm-css": "~0.2.3"
  }
}
```

Any idea what I'm doing wrong? 

I tried installing the packages to devDependencies, but that didn't fix the issue (nor did I expect it to from perusing the source).

**Comment by colllin** [comment]
Thanks @zedd45 .  I was having a similar issue.  Leaflet master has a "style" listing in package.json, but the latest stable (0.7.7) does not.
